---
- name: Converge
  hosts: all
  # Run one container at a time to avoid overwhelming the single ES instance
  serial: 1
  tasks:
    - name: Wait for ES to be reachable from this container
      ansible.builtin.uri:
        url: "http://elasticsearch-test:9200/_cluster/health"
        method: GET
        status_code: 200
      register: kibana_es_check
      retries: 30
      delay: 5
      until: kibana_es_check.status == 200

    - name: Include kibana role
      ansible.builtin.include_role:
        name: boutetnico.kibana
      vars:
        kibana_encryption_key: test-encryption-key-min-32-chars-long-12345
        kibana_elasticsearch_hosts:
          - "http://elasticsearch-test:9200"
        kibana_data_views:
          - name: "test-logs-*"
            default: true
        kibana_saved_objects_path: "{{ playbook_dir }}/files"
